name: Deploy Shared Resources
on: [push]

permissions:
      id-token: write
      contents: read
jobs: 
  plan:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}   
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/shared/uks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Format
        run: terraform fmt -check
      
      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}" -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}" -backend-config="container_name=${{ vars.TFSTATE_CONTAINER_NAME }}" -backend-config="key=${{ vars.TFSTATE_KEY }}"

      - name: Terraform Plan
        run: terraform plan -input=false -out tfplan

      - name: Upload TFPlan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ./terraform/shared/uks/tfplan

  apply:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}  
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/shared/uks
    runs-on: ubuntu-latest
    needs: plan
    environment: shared
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Download TFPlan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ./terraform/shared/uks

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}" -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}" -backend-config="container_name=${{ vars.TFSTATE_CONTAINER_NAME }}" -backend-config="key=${{ vars.TFSTATE_KEY }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan 
  destroy:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}  
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/shared/uks
    runs-on: ubuntu-latest
    needs: plan
    environment: shared
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}" -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}" -backend-config="container_name=${{ vars.TFSTATE_CONTAINER_NAME }}" -backend-config="key=${{ vars.TFSTATE_KEY }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve